[dependencies]
base = "0.10.4"
uuid = "1.0.0"

[package]
name = "swimming_pool"
version = "0.0.1"
description = "Collateralised Stablecoin Protocol"
repository = "https://github.com/SWMPool/SwimmingPool"
keywords = [ "swimming pool", "collateral", "stable", "token", "dfinity" ]
